workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - appstore_credentials
      vars:
        CM_CERTIFICATE: $CM_CERTIFICATE # Use the actual env variable name from Codemagic
        CM_CERTIFICATE_PASSWORD: $CM_CERTIFICATE_PASSWORD # Encrypted password for your certificate
        CM_PROVISIONING_PROFILE: $CM_PROVISIONING_PROFILE # Use the actual env variable name from Codemagic
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        PRIVATE_KEY: $PRIVATE_KEY
      flutter: stable # or your desired Flutter version
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Fetch code signing files
        script: |
          app-store-connect fetch-signing-files "jonnywcage@gmail.com" --type IOS_APP_STORE
          keychain add-certificates
      - name: Set up provisioning profiles
        script: |
          keychain add-provisioning-profiles
      - name: Build ipa
        script: |
          flutter build ios --release --build-number=$(git rev-list HEAD --count)
          cd ios
          xcode-project package-ipa --workspace ios/Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa

