workflows:
  flutter-app:
    name: Flutter App Build
    environment:
      flutter: stable
      vars:
        # Specify your environment variables here
        CM_CERTIFICATE: Encrypted(...) # Encrypted Apple Certificate
        CM_CERTIFICATE_PASSWORD: Encrypted(...) # Encrypted Certificate Password
        CM_PROVISIONING_PROFILE: Encrypted(...) # Encrypted Provisioning Profile
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build IPA
        script: |
          flutter build ios --release
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Add signing certificate to keychain
        script: |
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
      - name: Set up provisioning profiles
        script: |
          keychain add-provisioning-profiles --provisioning-profile /tmp/profile.mobileprovision
      - name: Export IPA
        script: |
          xcode-project use-profiles
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: "jonnywcage@gamil.com"
        # Encrypted App Specific Password
        
