workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - appstore_credential
      vars:
        CM_CERTIFICATE: Encrypted(...) # Use the actual env variable name from Codemagic
        CM_CERTIFICATE_PASSWORD: Encrypted(...) # Encrypted password for your certificate
        CM_PROVISIONING_PROFILE: Encrypted(...) # Use the actual env variable name from Codemagic
      flutter: stable # or your desired Flutter version
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Fetch code signing files
        script: |
          app-store-connect fetch-signing-files $YOUR_APPLE_APP_ID --type IOS_APP_STORE
          keychain add-certificates
      - name: Set up provisioning profiles
        script: |
          keychain add-provisioning-profiles
      - name: Build ipa
        script: |
          flutter build ios --release --build-number=$(git rev-list HEAD --count)
          cd ios
          xcode-project package-ipa --workspace ios/Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: jonnywcage@gmail.com # Your Apple email
        app_specific_password: Encrypted(...) # Your app-specific password
        app_store_connect_api_key:
          key_id: YOUR_KEY_ID
          issuer_id: YOUR_ISSUER_ID
          private_key: Encrypted(...) # The private key for App Store Connect API
        application_id: YOUR_APPLE_APP_ID