target 'Runner' do
  use_frameworks!

  # Specify the platform and version
  platform :ios, '12.0' # Use the iOS version you need

  # Add your CocoaPods dependencies here
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  # ...other pods...
end
